version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5001:5001'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=5001
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
